services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  web:
    image: shawnwxlex/releasevault:latest
    platform: linux/amd64
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - USE_DOCKER=1
      - DB_NAME=mydb
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=db
      - DB_PORT=3306
    command: >
      sh -c "
        until nc -z db 3306;
        do echo '⏳ Waiting for MySQL...'; sleep 2; done;
        echo '✅ MySQL is up - starting Django';
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"

volumes:
  db_data:
