# Generated by Django 2.2.24 on 2025-03-30 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
                'db_table': 'artist',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='MasterRelease',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core_Configuration.Artist')),
            ],
            options={
                'verbose_name': 'Master Release',
                'verbose_name_plural': 'Master Releases',
                'db_table': 'master_release',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('discogs_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('format', models.CharField(blank=True, default='Vinyl', max_length=50)),
                ('cover_url', models.CharField(blank=True, max_length=255)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core_Configuration.Artist')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core_Configuration.MasterRelease')),
            ],
            options={
                'verbose_name': 'Release',
                'verbose_name_plural': 'Releases',
                'db_table': 'release',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Wantlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core_Configuration.Release')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core_Configuration.User')),
            ],
            options={
                'verbose_name': 'Wantlist Entry',
                'verbose_name_plural': 'Wantlist Entries',
                'db_table': 'wantlist',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core_Configuration.Release')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core_Configuration.User')),
            ],
            options={
                'verbose_name': 'Collection Record',
                'verbose_name_plural': 'Collection Records',
                'db_table': 'collection',
            },
        ),
        migrations.CreateModel(
            name='ReleaseGenre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core_Configuration.Genre')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core_Configuration.Release')),
            ],
            options={
                'verbose_name': 'Release-Genre Mapping',
                'verbose_name_plural': 'Release-Genre Mappings',
                'db_table': 'release_genre',
                'unique_together': {('release', 'genre')},
            },
        ),
    ]
